version: '3'

services:
  switcher:
    build:
      context: .
      dockerfile: ./docker/switcher/Dockerfile 
    environment:
      - CYPRESS_USER_NAME
      - CYPRESS_PASSWORD
      - TZ
      - TARGET_ROUTER
    volumes:
      - ./data/videos:/usr/local/src/cypress/videos
      - ./data/screenshots:/usr/local/src/cypress/screenshots
      - ./data:/usr/local/data
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
    restart: always
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile 
    environment:
      - APPROVE_CODE
      - TZ
    ports:
      - 5000:5000
    volumes:
      - ./data:/usr/local/data
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
    restart: always
