version: '3'

services:
  wifi-switcher:
    build:
      context: .
      dockerfile: ./docker/Dockerfile 
    environment:
      - CYPRESS_USER_NAME
      - CYPRESS_PASSWORD
      - TZ
    volumes:
      - ./data/videos:/usr/local/src/cypress/videos
      - ./data/screenshots:/usr/local/src/cypress/screenshots
      - ./data/schedule.csv:/usr/local/data/schedule.csv
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
    restart: always
