version: '3'

services:
  switcher:
    build:
      context: .
      dockerfile: ./docker/switcher/Dockerfile 
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID?error}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY?error}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION?error}
      TABLE_NAME: ${TABLE_NAME?error}
      ROUTER_USER_NAME: ${ROUTER_USER_NAME:?error}
      ROUTER_PASSWORD: ${ROUTER_PASSWORD:?error}
      TARGET_ROUTER: ${TARGET_ROUTER?error}
      API_END_POINT: ${API_END_POINT:-http://web:5000}
      TZ: ${TZ:-Asia/Tokyo}
    volumes:
      - ./data/latest_logs:/usr/local/src/latest_logs
      - ./data/archived_logs:/usr/local/src/archived_logs
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
    restart: always
