version: '3'

services:
  wifi-switcher:
    build:
      context: .
      dockerfile: ./docker/Dockerfile 
    environment:
      - CYPRESS_USER_NAME
      - CYPRESS_PASSWORD
    volumes:
      - ./cron.conf:/var/spool/cron/crontabs/root
      - ./videos:/usr/local/src/cypress/videos
      - ./screenshots:/usr/local/src/cypress/screenshots
    logging:
      driver: 'json-file'
      options:
        max-size: 10m
    restart: always
